# =============================================================================
# JourneyMesh - Every journey, intelligently connected.
#
#   make setup     install everything (backend venv + deps, frontend deps, .env)
#   make dev       run the API and the interface together
#   make verify    run every test suite and a production build
#
# Author: Pankaj <pkp2.me2k9@gmail.com> - https://pankajpramanik.com
# =============================================================================

SHELL := /bin/bash
.DEFAULT_GOAL := help

# ---- Layout -----------------------------------------------------------------
BACKEND       := backend
FRONTEND      := frontend
VENV          := $(CURDIR)/$(BACKEND)/.venv
VENV_BIN      := $(VENV)/bin
PYTHON        ?= python3

# ---- Ports (override on the command line: make dev BACKEND_PORT=9000) -------
# ---- Docker -----------------------------------------------------------------
# Prefers the v2 plugin, falls back to the standalone binary.
COMPOSE       ?= $(shell docker compose version >/dev/null 2>&1 && echo "docker compose" || echo "docker-compose")
COMPOSE_DEV   := $(COMPOSE) -f docker-compose.yml -f docker-compose.dev.yml

BACKEND_PORT  ?= 8000
FRONTEND_PORT ?= 5173
API_URL       := http://127.0.0.1:$(BACKEND_PORT)
WEB_URL       := http://localhost:$(FRONTEND_PORT)

# ---- Cosmetics --------------------------------------------------------------
BOLD  := \033[1m
DIM   := \033[2m
BLUE  := \033[34m
GREEN := \033[32m
AMBER := \033[33m
RED   := \033[31m
OFF   := \033[0m

.PHONY: help setup check-tools venv backend-install backend-env frontend-install \
        frontend-env check-setup dev run backend-run frontend-dev stop \
        test backend-test frontend-test typecheck lint eval verify build \
        migrate migration health smoke clean reset info \
        docker-build docker-up docker-dev docker-down docker-restart docker-logs \
        docker-ps docker-migrate docker-test docker-shell docker-db docker-clean

# =============================================================================
# Help
# =============================================================================
help:
	@printf "$(BOLD)JourneyMesh$(OFF) - every journey, intelligently connected.\n\n"
	@printf "$(BOLD)Getting started$(OFF)\n"
	@printf "  $(BLUE)make setup$(OFF)            Install everything: venv, backend deps, frontend deps, .env files\n"
	@printf "  $(BLUE)make dev$(OFF)              Run the API and the interface together (Ctrl-C stops both)\n"
	@printf "  $(BLUE)make verify$(OFF)           Run every test suite plus a production build\n\n"
	@printf "$(BOLD)Run individually$(OFF)\n"
	@printf "  make backend-run          API only, on port $(BACKEND_PORT)\n"
	@printf "  make frontend-dev         Interface only, on port $(FRONTEND_PORT)\n"
	@printf "  make stop                 Stop anything left listening on those ports\n\n"
	@printf "$(BOLD)Quality$(OFF)\n"
	@printf "  make test                 Backend and frontend test suites\n"
	@printf "  make backend-test         pytest\n"
	@printf "  make frontend-test        vitest\n"
	@printf "  make typecheck            TypeScript project check\n"
	@printf "  make lint                 ruff\n"
	@printf "  make eval                 Offline evaluation suite\n"
	@printf "  make build                Production frontend build\n\n"
	@printf "$(BOLD)Database$(OFF)\n"
	@printf "  make migrate              Apply Alembic migrations (needs DATABASE_URL)\n"
	@printf "  make migration m=\"...\"    Create a new autogenerated revision\n\n"
	@printf "$(BOLD)Docker$(OFF)\n"
	@printf "  $(BLUE)make docker-up$(OFF)        Build and start the whole stack (db, API, interface)\n"
	@printf "  make docker-dev           Same stack with hot reload on both halves\n"
	@printf "  make docker-down          Stop the stack (add v=1 to drop the database volume)\n"
	@printf "  make docker-logs          Follow the logs (s=api to follow one service)\n"
	@printf "  make docker-ps            Show container status\n"
	@printf "  make docker-migrate       Run Alembic inside the stack\n"
	@printf "  make docker-test          Run the backend suite inside the API image\n"
	@printf "  make docker-shell         Shell into the API container (s=web for the interface)\n"
	@printf "  make docker-db            psql into the database\n\n"
	@printf "$(BOLD)Housekeeping$(OFF)\n"
	@printf "  make health               Read the health endpoint of a running API\n"
	@printf "  make smoke                Plan, revise and approve one journey end to end\n"
	@printf "  make info                 Show resolved paths, ports and setup state\n"
	@printf "  make clean                Remove caches and build output\n"
	@printf "  make reset                clean + remove the venv and node_modules\n\n"
	@printf "$(DIM)Ports: API $(BACKEND_PORT), interface $(FRONTEND_PORT). Override with e.g. make dev BACKEND_PORT=9000$(OFF)\n"

# =============================================================================
# Setup - one command
# =============================================================================
setup: check-tools venv backend-install backend-env frontend-install frontend-env
	@printf "\n$(GREEN)$(BOLD)JourneyMesh is ready.$(OFF)\n\n"
	@printf "  Next:  $(BOLD)make dev$(OFF)\n"
	@printf "         API        $(API_URL)/docs\n"
	@printf "         Interface  $(WEB_URL)\n\n"
	@printf "$(DIM)Every credential in backend/.env may stay empty - JourneyMesh runs offline\n"
	@printf "and labels every unconfirmed price as an ESTIMATE.$(OFF)\n"

check-tools:
	@printf "$(BOLD)Checking tools$(OFF)\n"
	@command -v $(PYTHON) >/dev/null 2>&1 || { printf "$(RED)$(PYTHON) not found. Install Python 3.11 or newer.$(OFF)\n"; exit 1; }
	@command -v npm >/dev/null 2>&1 || { printf "$(RED)npm not found. Install Node.js 18 or newer.$(OFF)\n"; exit 1; }
	@$(PYTHON) -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' || { printf "$(RED)Python 3.10 or newer is required.$(OFF)\n"; exit 1; }
	@printf "  python  %s\n" "$$($(PYTHON) --version 2>&1)"
	@printf "  node    %s\n" "$$(node --version 2>&1 || echo 'not found')"
	@printf "  npm     %s\n" "$$(npm --version)"

venv:
	@if [ ! -x "$(VENV_BIN)/python" ]; then \
		printf "$(BOLD)Creating the virtual environment$(OFF) ($(BACKEND)/.venv)\n"; \
		$(PYTHON) -m venv "$(VENV)" || { printf "$(RED)Could not create a venv. On Debian or Ubuntu: apt install python3-venv$(OFF)\n"; exit 1; }; \
	else \
		printf "$(DIM)Virtual environment already present$(OFF)\n"; \
	fi
	@"$(VENV_BIN)/python" -m pip install --quiet --upgrade pip

backend-install: venv
	@printf "$(BOLD)Installing backend dependencies$(OFF) (this takes a minute the first time)\n"
	@"$(VENV_BIN)/pip" install --quiet -r $(BACKEND)/requirements-dev.txt
	@printf "  done\n"

backend-env:
	@if [ ! -f $(BACKEND)/.env ]; then \
		cp $(BACKEND)/.env.example $(BACKEND)/.env; \
		printf "$(AMBER)Created $(BACKEND)/.env from the template - fill in credentials when you have them$(OFF)\n"; \
	else \
		printf "$(DIM)$(BACKEND)/.env already exists, leaving it alone$(OFF)\n"; \
	fi

frontend-install:
	@printf "$(BOLD)Installing frontend dependencies$(OFF)\n"
	@cd $(FRONTEND) && npm install --no-audit --no-fund --silent
	@printf "  done\n"

frontend-env:
	@if [ ! -f $(FRONTEND)/.env ]; then \
		cp $(FRONTEND)/.env.example $(FRONTEND)/.env; \
		printf "$(AMBER)Created $(FRONTEND)/.env from the template$(OFF)\n"; \
	else \
		printf "$(DIM)$(FRONTEND)/.env already exists, leaving it alone$(OFF)\n"; \
	fi

check-setup:
	@[ -x "$(VENV_BIN)/uvicorn" ] || { printf "$(RED)Backend is not set up yet. Run: $(BOLD)make setup$(OFF)\n"; exit 1; }
	@[ -d "$(FRONTEND)/node_modules" ] || { printf "$(RED)Frontend is not set up yet. Run: $(BOLD)make setup$(OFF)\n"; exit 1; }

# =============================================================================
# Run - one command for both halves
# =============================================================================
run: dev

dev: check-setup
	@printf "\n$(BOLD)Starting JourneyMesh$(OFF)\n"
	@printf "  $(BLUE)API$(OFF)        $(API_URL)  $(DIM)(docs at $(API_URL)/docs)$(OFF)\n"
	@printf "  $(BLUE)Interface$(OFF)  $(WEB_URL)\n"
	@printf "$(DIM)  Ctrl-C stops both.$(OFF)\n\n"
	@trap 'printf "\n$(DIM)stopping JourneyMesh...$(OFF)\n"; kill 0 2>/dev/null' INT TERM; \
	( cd $(BACKEND) && "$(VENV_BIN)/uvicorn" app.main:app --reload --port $(BACKEND_PORT) --no-server-header 2>&1 | sed -u 's/^/[api] /' ) & \
	( cd $(FRONTEND) && npm run dev --silent -- --port $(FRONTEND_PORT) 2>&1 | sed -u 's/^/[web] /' ) & \
	wait

backend-run: check-setup
	@cd $(BACKEND) && "$(VENV_BIN)/uvicorn" app.main:app --reload --port $(BACKEND_PORT) --no-server-header

frontend-dev:
	@cd $(FRONTEND) && npm run dev -- --port $(FRONTEND_PORT)

stop:
	@for port in $(BACKEND_PORT) $(FRONTEND_PORT); do \
		pid=$$(lsof -ti tcp:$$port 2>/dev/null); \
		if [ -n "$$pid" ]; then kill $$pid 2>/dev/null && printf "stopped the process on port %s\n" "$$port"; fi; \
	done
	@printf "$(DIM)ports $(BACKEND_PORT) and $(FRONTEND_PORT) are free$(OFF)\n"

# =============================================================================
# Quality
# =============================================================================
test: backend-test frontend-test

backend-test: check-setup
	@printf "$(BOLD)Backend tests$(OFF)\n"
	@cd $(BACKEND) && "$(VENV_BIN)/python" -m pytest -q

frontend-test:
	@printf "$(BOLD)Frontend tests$(OFF)\n"
	@cd $(FRONTEND) && npm run test:run --silent

typecheck:
	@cd $(FRONTEND) && npx tsc --noEmit && printf "$(GREEN)TypeScript is clean$(OFF)\n"

lint: check-setup
	@cd $(BACKEND) && "$(VENV_BIN)/python" -m ruff check app tests evals

eval: check-setup
	@printf "$(BOLD)Offline evaluation$(OFF)\n"
	@cd $(BACKEND) && "$(VENV_BIN)/python" -m evals.run_offline_eval

build:
	@cd $(FRONTEND) && npm run build

verify: backend-test frontend-test eval build
	@printf "\n$(GREEN)$(BOLD)Everything passed.$(OFF)\n"

# =============================================================================
# Database
# =============================================================================
migrate: check-setup
	@cd $(BACKEND) && "$(VENV_BIN)/alembic" upgrade head

migration: check-setup
	@if [ -z "$(m)" ]; then printf "$(RED)Usage: make migration m=\"describe the change\"$(OFF)\n"; exit 1; fi
	@cd $(BACKEND) && "$(VENV_BIN)/alembic" revision --autogenerate -m "$(m)"

# =============================================================================
# Checks against a running instance
# =============================================================================
health:
	@curl -fsS $(API_URL)/api/v1/health | $(PYTHON) -m json.tool || printf "$(RED)No API on $(API_URL). Start it with: make dev$(OFF)\n"

smoke:
	@$(PYTHON) scripts/smoke.py $(API_URL)

# =============================================================================
# Docker
# =============================================================================
docker-build:
	@$(COMPOSE) build

docker-up:
	@if [ ! -f .env ]; then cp .env.example .env; printf "$(AMBER)Created .env for the compose stack$(OFF)\n"; fi
	@$(COMPOSE) up --build -d
	@printf "\n$(GREEN)$(BOLD)JourneyMesh is running.$(OFF)\n"
	@printf "  Interface  http://localhost:$${WEB_PORT:-5173}\n"
	@printf "  API        http://localhost:$${API_PORT:-8000}/docs\n\n"
	@printf "$(DIM)  make docker-logs to follow, make docker-down to stop.$(OFF)\n"

docker-dev:
	@if [ ! -f .env ]; then cp .env.example .env; printf "$(AMBER)Created .env for the compose stack$(OFF)\n"; fi
	@printf "$(BOLD)Starting the stack with hot reload$(OFF) $(DIM)(Ctrl-C stops it)$(OFF)\n"
	@$(COMPOSE_DEV) up --build

docker-down:
	@if [ "$(v)" = "1" ]; then \
		printf "$(AMBER)Removing containers and the database volume$(OFF)\n"; \
		$(COMPOSE) down --volumes --remove-orphans; \
	else \
		$(COMPOSE) down --remove-orphans; \
	fi

docker-restart:
	@$(COMPOSE) restart $(or $(s),api web)

docker-logs:
	@$(COMPOSE) logs -f --tail=100 $(s)

docker-ps:
	@$(COMPOSE) ps

docker-migrate:
	@$(COMPOSE) run --rm migrate

docker-test:
	@$(COMPOSE) run --rm --no-deps -e DATABASE_URL= api pytest -q

docker-shell:
	@$(COMPOSE) exec $(or $(s),api) sh

docker-db:
	@$(COMPOSE) exec db psql -U $${POSTGRES_USER:-journeymesh} -d $${POSTGRES_DB:-journeymesh}

docker-clean:
	@$(COMPOSE) down --volumes --remove-orphans --rmi local
	@printf "$(DIM)containers, volumes and locally built images removed$(OFF)\n"


# =============================================================================
# Housekeeping
# =============================================================================
clean:
	@find $(BACKEND) -type d -name '__pycache__' -prune -exec rm -rf {} + 2>/dev/null || true
	@rm -rf $(BACKEND)/.pytest_cache $(BACKEND)/.ruff_cache $(BACKEND)/.coverage $(BACKEND)/htmlcov $(BACKEND)/evals/reports $(FRONTEND)/dist $(FRONTEND)/coverage $(FRONTEND)/node_modules/.vite
	@printf "$(DIM)caches and build output removed$(OFF)\n"

reset: clean
	@rm -rf $(VENV) $(FRONTEND)/node_modules
	@printf "$(DIM)venv and node_modules removed - run make setup to start again$(OFF)\n"

info:
	@printf "$(BOLD)JourneyMesh$(OFF)\n"
	@printf "  root           $(CURDIR)\n"
	@printf "  venv           %s\n" "$$([ -x '$(VENV_BIN)/python' ] && echo 'ready' || echo 'missing - run make setup')"
	@printf "  node_modules   %s\n" "$$([ -d '$(FRONTEND)/node_modules' ] && echo 'ready' || echo 'missing - run make setup')"
	@printf "  backend .env   %s\n" "$$([ -f '$(BACKEND)/.env' ] && echo 'present' || echo 'missing')"
	@printf "  frontend .env  %s\n" "$$([ -f '$(FRONTEND)/.env' ] && echo 'present' || echo 'missing')"
	@printf "  API port       $(BACKEND_PORT)\n"
	@printf "  web port       $(FRONTEND_PORT)\n"
