"""Server-side phrase catalogue.

Agents produce *codes* for every sentence they generate, and the Final
Response Agent renders those codes in the traveller's chosen language. That
keeps the multilingual output deterministic: it does not depend on a
translation model being configured, and it cannot drift between revisions.

The frontend has its own catalogue for interface strings; this one covers the
sentences that are generated by the backend.
"""

from __future__ import annotations

from typing import Any

from app.core.constants import DEFAULT_LANGUAGE, SUPPORTED_LANGUAGES

PHRASES: dict[str, dict[str, str]] = {
    # ---- journey framing -------------------------------------------------
    "journey.title": {
        "en": "{days}-day journey to {destination}",
        "bn": "{destination}-এ {days} দিনের ভ্রমণ",
        "hi": "{destination} की {days} दिन की यात्रा",
    },
    "journey.title_no_days": {
        "en": "Journey to {destination}",
        "bn": "{destination}-এ ভ্রমণ",
        "hi": "{destination} की यात्रा",
    },
    "journey.headline": {
        "en": "A {style} plan for {travelers} traveller(s), built around {interests}.",
        "bn": "{travelers} জন ভ্রমণকারীর জন্য একটি {style} পরিকল্পনা, {interests} ঘিরে সাজানো।",
        "hi": "{travelers} यात्रियों के लिए एक {style} योजना, {interests} पर केंद्रित।",
    },
    "journey.headline_simple": {
        "en": "A {style} plan for {travelers} traveller(s).",
        "bn": "{travelers} জন ভ্রমণকারীর জন্য একটি {style} পরিকল্পনা।",
        "hi": "{travelers} यात्रियों के लिए एक {style} योजना।",
    },
    "journey.closing": {
        "en": "Your journey is approved and saved. Safe travels.",
        "bn": "আপনার ভ্রমণ পরিকল্পনা অনুমোদিত ও সংরক্ষিত হয়েছে। শুভ যাত্রা।",
        "hi": "आपकी यात्रा योजना स्वीकृत और सहेजी गई है। यात्रा शुभ हो।",
    },
    "journey.closing_estimates": {
        "en": (
            "Your journey is approved and saved. Prices marked as estimates should be "
            "confirmed with the provider before booking."
        ),
        "bn": (
            "আপনার ভ্রমণ পরিকল্পনা অনুমোদিত ও সংরক্ষিত হয়েছে। আনুমানিক হিসেবে চিহ্নিত "
            "দামগুলো বুকিংয়ের আগে সরবরাহকারীর কাছ থেকে নিশ্চিত করে নিন।"
        ),
        "hi": (
            "आपकी यात्रा योजना स्वीकृत और सहेजी गई है। अनुमानित बताए गए दामों की पुष्टि "
            "बुकिंग से पहले प्रदाता से कर लें।"
        ),
    },
    # ---- packing ---------------------------------------------------------
    "packing.hot": {
        "en": "Light breathable clothing, a sun hat and high-SPF sunscreen.",
        "bn": "হালকা আরামদায়ক পোশাক, রোদটুপি এবং উচ্চ এসপিএফ সানস্ক্রিন নিন।",
        "hi": "हल्के हवादार कपड़े, धूप की टोपी और हाई-SPF सनस्क्रीन रखें।",
    },
    "packing.very_hot": {
        "en": "Plan outdoor time before 10:00 or after 17:00 and carry water.",
        "bn": "বাইরের ঘোরাঘুরি সকাল ১০টার আগে বা বিকেল ৫টার পরে রাখুন এবং পানি সঙ্গে নিন।",
        "hi": "बाहर घूमना सुबह 10 बजे से पहले या शाम 5 बजे के बाद रखें और पानी साथ लें।",
    },
    "packing.cool": {
        "en": "A warm mid-layer and a windproof jacket for the evenings.",
        "bn": "সন্ধ্যার জন্য একটি গরম মিড-লেয়ার ও বাতাস আটকানো জ্যাকেট নিন।",
        "hi": "शाम के लिए एक गर्म मिड-लेयर और विंडप्रूफ जैकेट रखें।",
    },
    "packing.freezing": {
        "en": "Gloves, a hat and insulated footwear.",
        "bn": "দস্তানা, টুপি এবং গরম জুতা নিন।",
        "hi": "दस्ताने, टोपी और गर्म जूते रखें।",
    },
    "packing.rain": {
        "en": "A compact umbrella or rain shell, and quick-drying shoes.",
        "bn": "ছোট ছাতা বা রেইন জ্যাকেট এবং দ্রুত শুকানো জুতা নিন।",
        "hi": "छोटा छाता या रेन जैकेट और जल्दी सूखने वाले जूते रखें।",
    },
    "packing.humid": {
        "en": "Humidity is high; pack an extra change of clothes per day.",
        "bn": "আর্দ্রতা বেশি; প্রতিদিনের জন্য বাড়তি এক সেট পোশাক নিন।",
        "hi": "नमी अधिक है; हर दिन के लिए एक अतिरिक्त जोड़ी कपड़े रखें।",
    },
    "packing.layers": {
        "en": "Comfortable layers work well for this forecast.",
        "bn": "এই পূর্বাভাসে আরামদায়ক লেয়ারই যথেষ্ট।",
        "hi": "इस पूर्वानुमान के लिए आरामदायक लेयर पर्याप्त हैं।",
    },
    # ---- weather-driven suggestions -------------------------------------
    "weather.indoor_ready": {
        "en": "Keep indoor options ready for {dates}.",
        "bn": "{dates} তারিখে ঘরের ভিতরের বিকল্প হাতে রাখুন।",
        "hi": "{dates} के लिए इनडोर विकल्प तैयार रखें।",
    },
    "weather.morning_walks": {
        "en": "Shift walking tours to the morning on the hottest days.",
        "bn": "সবচেয়ে গরম দিনগুলোতে হাঁটার ভ্রমণ সকালে সরিয়ে নিন।",
        "hi": "सबसे गर्म दिनों में पैदल भ्रमण सुबह कर लें।",
    },
    "weather.outdoor_ok": {
        "en": "Conditions look suitable for outdoor sightseeing throughout.",
        "bn": "পুরো সময় বাইরের ঘোরাঘুরির জন্য আবহাওয়া অনুকূল মনে হচ্ছে।",
        "hi": "पूरे समय बाहर घूमने के लिए मौसम अनुकूल लग रहा है।",
    },
    "weather.check_again": {
        "en": "Check the forecast again closer to departure.",
        "bn": "যাত্রার কাছাকাছি সময়ে পূর্বাভাস আবার দেখে নিন।",
        "hi": "प्रस्थान के करीब मौसम पूर्वानुमान दोबारा देखें।",
    },
    "weather.kids_midday": {
        "en": "With children in the party, keep midday hours indoors on the hottest days.",
        "bn": "দলে শিশু থাকলে সবচেয়ে গরম দিনগুলোর দুপুর ঘরের ভিতরে কাটান।",
        "hi": "समूह में बच्चे हों तो सबसे गर्म दिनों की दोपहर घर के भीतर बिताएँ।",
    },
    # ---- itinerary tips --------------------------------------------------
    "tip.family_rooms": {
        "en": "Book family rooms early - they sell out before standard rooms.",
        "bn": "ফ্যামিলি রুম আগেভাগে বুক করুন - সাধারণ রুমের আগেই সেগুলো শেষ হয়ে যায়।",
        "hi": "फैमिली रूम पहले बुक करें - ये सामान्य कमरों से पहले भर जाते हैं।",
    },
    "tip.special_requirements": {
        "en": "Confirm your special requirements directly with the hotel before arrival.",
        "bn": "পৌঁছানোর আগে আপনার বিশেষ প্রয়োজনগুলো হোটেলের সঙ্গে সরাসরি নিশ্চিত করুন।",
        "hi": "पहुँचने से पहले अपनी विशेष ज़रूरतें होटल से सीधे पक्की कर लें।",
    },
    "tip.transit_card": {
        "en": "Carry a local transit card; it is usually cheaper than single tickets.",
        "bn": "স্থানীয় ট্রানজিট কার্ড রাখুন; একক টিকিটের চেয়ে সাধারণত সস্তা।",
        "hi": "स्थानीय ट्रांजिट कार्ड रखें; यह आमतौर पर सिंगल टिकट से सस्ता पड़ता है।",
    },
    "tip.confirm_prices": {
        "en": "Confirm flight and hotel prices with the provider before committing.",
        "bn": "চূড়ান্ত করার আগে ফ্লাইট ও হোটেলের দাম সরবরাহকারীর কাছ থেকে নিশ্চিত করুন।",
        "hi": "अंतिम रूप देने से पहले उड़ान और होटल के दाम प्रदाता से पक्के कर लें।",
    },
    # ---- budget verdicts -------------------------------------------------
    "budget.within": {
        "en": "The plan fits inside your budget with {remaining} {currency} to spare.",
        "bn": "পরিকল্পনাটি আপনার বাজেটের মধ্যেই আছে, {remaining} {currency} বাকি থাকছে।",
        "hi": "योजना आपके बजट के भीतर है, {remaining} {currency} बच रहे हैं।",
    },
    "budget.near_limit": {
        "en": "The plan uses almost your whole budget.",
        "bn": "পরিকল্পনাটি আপনার প্রায় পুরো বাজেট ব্যবহার করছে।",
        "hi": "योजना आपका लगभग पूरा बजट इस्तेमाल कर रही है।",
    },
    "budget.over": {
        "en": "The plan is about {over} {currency} over your budget.",
        "bn": "পরিকল্পনাটি আপনার বাজেটের চেয়ে প্রায় {over} {currency} বেশি।",
        "hi": "योजना आपके बजट से लगभग {over} {currency} अधिक है।",
    },
    "budget.insufficient": {
        "en": "No budget was set, so the total shown is a planning estimate.",
        "bn": "কোনো বাজেট দেওয়া হয়নি, তাই দেখানো মোটটি একটি আনুমানিক হিসাব।",
        "hi": "कोई बजट नहीं दिया गया, इसलिए दिखाया गया कुल एक अनुमान है।",
    },
    # ---- data provenance -------------------------------------------------
    "provenance.estimates": {
        "en": "Prices marked ESTIMATE come from JourneyMesh planning models, not a live provider.",
        "bn": "ESTIMATE চিহ্নিত দামগুলো JourneyMesh-এর পরিকল্পনা মডেল থেকে, সরাসরি সরবরাহকারী থেকে নয়।",
        "hi": "ESTIMATE लिखे दाम JourneyMesh के प्लानिंग मॉडल से हैं, किसी लाइव प्रदाता से नहीं।",
    },
    "provenance.live": {
        "en": "Prices marked LIVE were confirmed by the provider at the time shown.",
        "bn": "LIVE চিহ্নিত দামগুলো উল্লিখিত সময়ে সরবরাহকারী নিশ্চিত করেছে।",
        "hi": "LIVE लिखे दाम बताए गए समय पर प्रदाता द्वारा पुष्ट किए गए थे।",
    },
    # ---- travel styles ---------------------------------------------------
    "style.budget": {"en": "budget", "bn": "সাশ্রয়ী", "hi": "किफ़ायती"},
    "style.comfort": {"en": "comfortable", "bn": "আরামদায়ক", "hi": "आरामदायक"},
    "style.luxury": {"en": "luxury", "bn": "বিলাসবহুল", "hi": "लक्ज़री"},
    "style.adventure": {"en": "adventurous", "bn": "অ্যাডভেঞ্চারধর্মী", "hi": "साहसिक"},
    "style.family": {"en": "family", "bn": "পরিবারবান্ধব", "hi": "पारिवारिक"},
    "style.business": {"en": "business", "bn": "ব্যবসায়িক", "hi": "व्यावसायिक"},
    "style.relaxed": {"en": "relaxed", "bn": "নিরিবিলি", "hi": "आरामभरी"},
    # ---- interests -------------------------------------------------------
    "interest.food": {"en": "food", "bn": "খাবার", "hi": "खानपान"},
    "interest.nature": {"en": "nature", "bn": "প্রকৃতি", "hi": "प्रकृति"},
    "interest.history": {"en": "history", "bn": "ইতিহাস", "hi": "इतिहास"},
    "interest.culture": {"en": "culture", "bn": "সংস্কৃতি", "hi": "संस्कृति"},
    "interest.shopping": {"en": "shopping", "bn": "কেনাকাটা", "hi": "खरीदारी"},
    "interest.beaches": {"en": "beaches", "bn": "সমুদ্রসৈকত", "hi": "समुद्र तट"},
    "interest.nightlife": {"en": "nightlife", "bn": "রাতের জীবন", "hi": "नाइटलाइफ़"},
    "interest.photography": {"en": "photography", "bn": "ফটোগ্রাফি", "hi": "फ़ोटोग्राफ़ी"},
    "interest.technology": {"en": "technology", "bn": "প্রযুক্তি", "hi": "तकनीक"},
    "interest.family_activities": {
        "en": "family activities",
        "bn": "পরিবারের কার্যক্রম",
        "hi": "पारिवारिक गतिविधियाँ",
    },
    # ---- review ----------------------------------------------------------
    "review.awaiting": {
        "en": "Review this draft and either approve it or tell JourneyMesh what to change.",
        "bn": "এই খসড়াটি দেখে অনুমোদন দিন অথবা কী বদলাতে চান JourneyMesh-কে জানান।",
        "hi": "इस मसौदे को देखें और स्वीकृत करें या बताएँ कि JourneyMesh क्या बदले।",
    },
    "review.limit_reached": {
        "en": (
            "This journey has reached its revision limit. Approve the current plan or "
            "start a new journey."
        ),
        "bn": (
            "এই ভ্রমণ পরিকল্পনার সংশোধনের সীমা শেষ। বর্তমান পরিকল্পনা অনুমোদন করুন অথবা "
            "নতুন করে পরিকল্পনা শুরু করুন।"
        ),
        "hi": (
            "इस यात्रा की संशोधन सीमा पूरी हो गई है। मौजूदा योजना स्वीकृत करें या नई यात्रा "
            "शुरू करें।"
        ),
    },
}


def translate(code: str, language: str = DEFAULT_LANGUAGE, **values: Any) -> str:
    """Render ``code`` in ``language``, falling back to English."""
    entry = PHRASES.get(code)
    if entry is None:
        return code
    lang = language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE
    template = entry.get(lang) or entry.get(DEFAULT_LANGUAGE) or code
    if not values:
        return template
    try:
        return template.format(**values)
    except (KeyError, IndexError):
        return template


def translate_all(codes: list[Any], language: str = DEFAULT_LANGUAGE) -> list[str]:
    """Render a list of codes, or of ``[code, values]`` pairs."""
    rendered: list[str] = []
    for item in codes:
        if isinstance(item, str):
            rendered.append(translate(item, language))
        elif isinstance(item, (list, tuple)) and item:
            code = str(item[0])
            values = item[1] if len(item) > 1 and isinstance(item[1], dict) else {}
            rendered.append(translate(code, language, **values))
    return list(dict.fromkeys(rendered))


def has(code: str) -> bool:
    return code in PHRASES
